[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/create-account"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[dev]
  command = "npm run dev"